FROM java:8-jre-alpine
COPY build/libs/Resolution-Engine-0.0.1-SNAPSHOT.jar /app/Resolution-Engine-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "\/app\/Resolution-Engine-0.0.1-SNAPSHOT.jar"]
