swagger: '2.0'
info:
  title: VDC Resolution Engine
  version: 0.0.1
paths:
  /searchBlueprintByReq:
    post:
      description: Blueprint Filtering
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ApplicationRequirements
          in: body
          description: Requirements posed by the application designer
          required: true
          schema:
            type: object
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: object
              properties:
                blueprint:
                  type: object
                score:
                  type: number
                methodNames:
                  type: array
                  items:
                    type: string
