swagger: '2.0'
info:
  title: VDC Resolution Engine
  version: 0.0.1
paths:
  /searchBlueprintByReq:
    post:
      description: Blueprint Filtering
      consumes:
        - application/json
      produces:
        - application/json;charset=UTF-8
      parameters:
        - name: ApplicationRequirements
          in: body
          description: Requirements posed by the application designer
          required: true
          schema:
            type: object
            example:
              applicationType: batch
              functionalRequirements:
                methodTags:
                  - anomaly detection
                vdcTags:
                  - machines
                schema:
                  attributes:
                    - ask_iccs
              attributes:
                dataUtility:
                  - id: availability_90
                    description: Availability 90
                    type: Availability
                    properties:
                      availability:
                        unit: percentage
                        minimum: 90
                  - id: responseTime_2
                    description: ResponseTime 2
                    type: ResponseTime
                    properties:
                      responseTime:
                        maximum: 4
                        unit: second
                  - id: timeliness
                    description: Timeliness
                    type: Timeliness
                    properties:
                      timeliness:
                        minimum: 90
                        unit: percentage
                  - id: volume_1200
                    description: volume 1200
                    type: Volume
                    properties:
                      volume:
                        minimum: 1200
                        unit: tuple
                security:
                  - id: encryption_AES128
                    description: Encryption AES 128
                    type: TransportEncryption
                    properties:
                      protocol:
                        unit: enum
                        value: TLS
                      algorithm:
                        unit: list
                        value:
                          - TLS_AES_256_GCM_SHA384
                          - TLS_AES_128_GCM_SHA256
                          - TLS_AES_128_CCM_8_SHA256
                          - TLS_AES_128_CCM_SHA256
                      keyLength:
                        unit: number
                        value: 128
                  - id: accessControl_direct
                    description: Access control Direct
                    type: AccessControl
                    properties:
                      Protocol:
                        value: 'Direct, OAuth'
                privacy: []
              goalTrees:
                dataUtility:
                  description: Requirements achieved
                  type: AND
                  children:
                    - description: High QoS
                      type: AND
                      leaves:
                        - id: serviceAvailable
                          description: Service available
                          weight: 1
                          attributes:
                            - availability_90
                        - id: fastProcess
                          description: Fast process
                          weight: 1
                          attributes:
                            - responseTime_2
                    - description: High Data Quality
                      type: AND
                      leaves:
                        - id: freshData
                          description: Fresh data
                          weight: 1
                          attributes:
                            - timeliness
                        - id: EnoughData
                          description: Enough amount of Data
                          weight: 1
                          attributes:
                            - volume_1200
                security:
                  type: AND
                  description: High security
                  leaves:
                    - id: TrasportEncryption
                      description: Secure data trasport
                      weight: 1
                      attributes:
                        - encryption_AES128
                    - id: AccessControl
                      description: Secure access
                      weight: 1
                      attributes:
                        - accessControl_direct
              methodsOutput:
                methods:
                  - method_id: GetSimplifiedDiagnostic
                    attributes:
                      - status
                      - timestamp
                      - cause
                  - method_id: GetFullDiagnostic
                    attributes:
                      - status
                      - timestamp
                      - cause
              providedResources:
                infrastructures:
                  - name: spart-fog-infrastructure
                    type: fog
                    provider:
                      api_endpoint: ip_removed
                      apy_tpye: kubernetes
                      credentials:
                        config:
                          apiVersion: v1
                          clusters:
                            - cluster:
                                certificate-authority-data: removed
                                server: 'https://ip_removed:36443'
                              name: kubernetes
                          contexts:
                            - context:
                                cluster: kubernetes
                                user: kubernetes-admin
                              name: kubernetes-admin@kubernetes
                          current-context: kubernetes-admin@kubernetes
                          kind: Config
                          preferences: {}
                          users:
                            - name: kubernetes-admin
                              user:
                                client-certificate-data: removed
                                client-key-data: removed
                    extra_properties:
                      owner: ApplicationDeveloper
                      ditas_default: true
                    resources:
                      - name: spart-fog-server-1
                        cpu: 1830
                        ram: 8000
                        disk: 480000
                        drives: []
                        role: master
                  - name: spart-edge-infrastructure
                    type: edge
                    provider:
                      api_endpoint: ip_removed
                      apy_tpye: kubernetes
                      credentials:
                        config:
                          apiVersion: v1
                          clusters:
                            - cluster:
                                certificate-authority-data: removed
                                server: 'https://ip_removed:36444'
                              name: kubernetes
                          contexts:
                            - context:
                                cluster: kubernetes
                                user: kubernetes-admin
                              name: kubernetes-admin@kubernetes
                          current-context: kubernetes-admin@kubernetes
                          kind: Config
                          preferences: {}
                          users:
                            - name: kubernetes-admin
                              user:
                                client-certificate-data: removed
                                client-key-data: removed
                    extra_properties:
                      owner: ApplicationDeveloper
                    resources:
                      - name: spart-edge-server-1
                        cpu: 1830
                        ram: 4000
                        disk: 120000
                        drives: []
                        role: master
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: object
              properties:
                blueprint:
                  type: object
                score:
                  type: number
                methodNames:
                  type: array
                  items:
                    type: string
